### ISSUE TITLE
Python dosyasını ilk kez açarken hata

### ISSUE THREAD

**Issue by andachamamci** [ImagingYeditepe/NuNuTRUBA#3]
Bir python dosyasını ilk kez seçerken yani içinde parametreler yoksa şu hata mesajını alıyorum:
![image](https://user-images.githubusercontent.com/46162005/103463391-0d838900-4d3d-11eb-87d6-1b6587049798.png)

**Comment by andachamamci** [comment]
Eğer parametreleri bulamazsa kendisi default parametreleri ekleyip o şekilde açmalı.

**Comment by YTPGozde** [comment]
Parametreler için gerekli comment satırları olmayan dosyayı kullanmaz. Bu konuda bir güncelleme yapılabilir.

**Comment by YTPGozde** [comment]
İstenilen özelliğin sistemini arayüze ekledim. İçinde comment satırları olmayan dosyayı da seçebilirsiniz. Güncel hali paylaşıldı. Düzenle kısmı için de güncelleme gelebilir.
