### ISSUE TITLE
Truba sunucusunda çalıştırırken hata

### ISSUE THREAD

**Issue by andachamamci** [ImagingYeditepe/NuNuTRUBA#4]
Truba sunucusuna kod gönderirken şu hatayı alıyorum:
![image](https://user-images.githubusercontent.com/46162005/103479191-16c43280-4ddd-11eb-86ce-e02ddc977efc.png)

Gönderdiğim dosya sunucuda görünmüyor.

Bir **log dosyası** oluştursan ve program yaptığı tüm işlemleri loga yazsa. _Şu dosyayı gönderiyorum. Bu komutu çalıştırıyorum._ gibi

**Comment by andachamamci** [comment]
Karşıdaki ev dizini **/truba/home/username/** olarak geçiyor. Sadece **/home/username/** değil. Alternatif olarak **~/** de aynı dizini göstermek için kullanılabiliyor.

**Comment by YTPGozde** [comment]
Bir TRUBA kullanıcısının bileceği bir bilgi, kullanıcıdan duymadığım bir bilgi olduğu için eksik kalmış. Eklenebilir bir şey tabi eklerim. Virtualboxla kullanım testinde sıkıntısızdı o yüzden ben öyle kullanmıştım. TRUBA'da farklıymış meğerse şimdi öğrenmiş oldum ben de teşekkürler. İlerleyen süreçte güncellenecek.

**Comment by YTPGozde** [comment]
Adres hatası düzeltildi. Güncel hali yüklendi.
