### ISSUE TITLE
Çalışan işlerin durumunu göstermek

### ISSUE THREAD

**Issue by andachamamci** [ImagingYeditepe/NuNuTRUBA#6]
Ana sayfada TRUBAda çalışan işlerin durumunu listelemek gerek. Bunun için **sacct** komutunun verdiği listeyi alıp yerelde göstermek lazım (**ls**'in çıktısını göstermek gibi. Test için **ls**'i kullanabiliriz). iptal etme tuşu da olmalı **scancel jobid** göndererek.
![image](https://user-images.githubusercontent.com/46162005/104315611-46b1bb00-54ec-11eb-8954-7fd7fa772702.png)

**Comment by YTPGozde** [comment]
Komut özelliği eklendi.
Varsayılan olarak "sacct" komutu eklendi.
Çalıştır butonuna tıklandığında çalışır.
Değiştirmek istendiğinirse entry girilip düzenleye tıklandığında değiştirilebilir.
