### ISSUE TITLE
İş gönderme ekranındaki parametreler

### ISSUE THREAD

**Issue by andachamamci** [ImagingYeditepe/NuNuTRUBA#7]
İş gönderirken dosyanın içindeki parametreleri edit etmek gerekir:

![image](https://user-images.githubusercontent.com/46162005/104316099-09016200-54ed-11eb-925a-faf62d3dda4e.png)

**PARAMETRELER ŞUNLAR:**
_#NuNuTRUBA_KUYRUK=short:
#NuNuTRUBA_CPUSAYISI=4:
#NuNuTRUBA_GPUSAYISI=1:
#NuNuTRUBA_PIP=numpy,sys:
#NuNuTRUBA_PARAMETRELER=1,2,3:
#NuNuTRUBA_GIDENDOSYALAR=dosya1,dosya2:
#NuNuTRUBA_DONENDOSYALAR=dosya,dosya:_

Diyalog açılırken dosyanın içinden okuyarak doldurması ve kullanıcının isterse buradan değişiklik yapabilmesi kullanışlı olur. Yukarıda job parametrelerini görmek kullanışlı bence öyle kalabilir.

**Comment by YTPGozde** [comment]
Edit ekranı güncellendi. Kullanıcı job'da olacak değişikleri sadece py dosyasını görerek yapabilir. Parametreler, giden dosyalar, dönen dosyalar da editle değiştirilebilir.
